### PR TITLE
fix example in README.md and add make the full example more prominent

### PR DESCRIPTION
**Pull request by zoechi**

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Could you change the lib rather than the documentation?  I believe it should be used as `Wiretap` rather than just `Tap`.

Awesome work!

**Comment by zoechi** [comment]
`new Wiretap()` threw an error, `new Tap()` worked fine

**Comment by robertleeplummerjr** [comment]
You are right.  What I mean is would you mind changing the first line of the lib to: `var Wiretap =...` rather than `var Tap =...`?  Thanks again for your hard work and finding this bug.

**Comment by zoechi** [comment]
I'm not a JS dev. I'm working with Dart and just needed a way to get events fired from components automatically after page-load.
I don't know how to change the code to make it work this way. I leave it to you, feel free to close the PR.

**Comment by robertleeplummerjr** [comment]
It all good.  Thanks again!

**Pull request merged**
